In [23]:
import pandas as pd
import cutecharts.charts as ctc
import matplotlib.pyplot as plt

In [16]:
# import csv file
data = pd.read_csv('severe-storms.csv')
data

,Year,Severe Storm Count,Severe Storm Cost,Severe Storm Lower 95,Severe Storm Upper 95
0,2001,2,6.6,5.6,7.3
1,2002,2,4.8,4.1,5.5
2,2003,4,13.4,11.2,16.1
3,2004,2,2.7,2.3,3.4
4,2005,1,1.4,1.1,1.4
5,2006,5,10.6,9.1,11.8
6,2007,1,3.7,3.1,3.9
7,2008,6,12.9,11.1,14.5
8,2009,6,11.5,10.1,12.2
9,2010,4,12.6,11.8,15.1
10,2011,10,44.0,37.7,51.7
11,2012,7,22.0,19.6,23.5
12,2013,7,14.2,12.6,16.0
13,2014,7,15.6,14.4,17.5
14,2015,6,10.6,9.7,12.4
15,2016,8,18.8,15.7,20.2
16,2017,11,24.1,20.7,28.0
17,2018,10,16.5,13.8,20.2
18,2019,8,16.6,13.9,20.6
19,2020,13,39.7,33.7,47.2
20,2021,11,22.5,17.4,27.4
21,2022,11,22.4,18.7,25.4
22,2023,19,54.0,44.3,61.8

In [38]:
def create_line_chart(data):
    # Extracting the required data
    years = data['Year'].tolist()
    storm_counts = data['Severe Storm Count'].tolist()
    
    # Creating the line chart
    chart = ctc.Line("Severe Storm Count Over Years", width='900px', height='200px')
    chart.set_options(labels=years, x_label="Year", y_label="Severe Storm Count", colors=['#9B3192'])
    chart.add_series("Severe Storm Count", storm_counts)
    
    # Rendering the chart to an HTML file
    chart.render('severe_storm_count_over_years.html')

create_line_chart(data)

In [36]:
def create_bar_chart(data):
    # Extracting the required data
    years = data['Year'].astype(str).tolist()  # Convert years to string for cutecharts
    storm_costs = data['Severe Storm Cost'].tolist()
    
    # Creating the bar chart
    chart = ctc.Bar("Severe Storm Costs Over Years (estimates)", width='1000px', height='200px')
    chart.set_options(labels=years, x_label="Year", 
                      y_label="Severe Storm Cost ($ Billion), CPI Adjusted",
                      colors=['#FFF1C9', '#FFF1C9', '#FFF1C9', '#FFF1C9', '#FFF1C9', '#FFF1C9', '#FFF1C9', 
                                '#F7B7A3', '#F7B7A3', '#F7B7A3', '#F7B7A3', '#F7B7A3', '#F7B7A3', '#F7B7A3',
                                '#EA5F89', '#EA5F89', '#EA5F89', '#EA5F89', '#EA5F89', '#EA5F89',
                                '#9B3192','#9B3192', '#57167E'])
    chart.add_series("Severe Storm Cost", storm_costs)
    
    
    # Rendering the chart to an HTML file
    chart.render('severe_storm_costs.html')

# Run the function
create_bar_chart(data)